const cartActionTypes = {
	ADD_ITEM: "ADD_ITEM",
	DECREASE_ITEM: "DECREASE_ITEM",
	CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
	ADD_ITEM_TO_WISHLIST: "ADD_ITEM_TO_WISHLIST"
};

export default cartActionTypes;
